language: python
python:
  - 3.4
  - 3.5
  - 3.6

os:
    - linux

compiler:
    - gcc

services: docker
sudo: required

env:
    global:
        - UNICODE_WIDTH=32
        - PLAT=x86_64
        - MB_PYTHON_VERSION=$TRAVIS_PYTHON_VERSION
        - VERSION=$(echo $TRAVIS_TAG | sed s/v//)
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

addons:
    apt:
        sources:
            - george-edison55-precise-backports # cmake 3
            - ubuntu-toolchain-r-test # gcc-7
        packages:
            - cmake
            - cmake-data
            - g++-7

matrix:
    fast_finish: true
    include:
        - python: 3.7
          dist: xenial
          sudo: true
        - os: linux
          compiler: clang
          env:
              - MATRIX_EVAL="CC=clang && CXX=clang++"
              - SCAN="scan-build --status-bugs"
              - SOURCEDEPLOY=1
              - WERROR="-DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS=-Werror"
        - os: osx
          language: generic
          python: 3.4
          env:
            - MB_PYTHON_VERSION=3.4
            - MACOSX_DEPLOYMENT_TARGET=10.9
        - os: osx
          python: 3.5
          language: generic
          env:
            - MB_PYTHON_VERSION=3.5
            - MACOSX_DEPLOYMENT_TARGET=10.9
        - os: osx
          language: generic
          python: 3.6
          env:
            - MB_PYTHON_VERSION=3.6
            - MACOSX_DEPLOYMENT_TARGET=10.9
        - os: osx
          language: generic
          python: 3.7
          env:
            - MB_PYTHON_VERSION=3.7
            - MACOSX_DEPLOYMENT_TARGET=10.9

before_install:
    - eval "${MATRIX_EVAL}"
    - unset -f pushd
    - unset -f popd
    - git clone https://github.com/matthew-brett/multibuild
    - source multibuild/common_utils.sh
    - source multibuild/travis_steps.sh
    - before_install

install:
    - pip install bandit
                  numpy
                  setuptools
                  setuptools_scm
                  pytest
                  pytest-runner
                  pybind11
                  hypothesis
    - bandit -c bandit.yml -r python/

before_script:
    - mkdir build
    - pushd build
    - $SCAN cmake -DCMAKE_BUILD_TYPE=Release
                  -DBUILD_SHARED_LIBS=ON
                  -DCMAKE_INSTALL_NAME_DIR=/usr/local/lib
                  ${WERROR}
                  ..
    - popd

# distutils/setuptools on macos ignores the --rpath argument, so set
# DYLD_LIBRARY_PATH so that the freshly-built image is picked up on for the
# tests.
#
# the build is configured with CMAKE_INSTALL_NAME_DIR so that in the wheel
# build on OS X, the delocate tool can figure out what dylib to include.
script:
    - pushd build
    - export DYLD_LIBRARY_PATH=$PWD/lib
    - make
    - ctest --output-on-failure
    - sudo make install
    - popd
    - build_wheel python $PLAT
    - install_run $PLAT
    - mv wheelhouse python/dist

before_deploy:
    - pushd python

after_deploy:
    - popd

deploy:
    - provider: pypi
      skip_cleanup: true
      skip_upload_docs: true
      user: statoil-travis
      distributions: build
      password:
        secure: lov28Jwk7zhWn4O9TAahp+NVbdhppnVmJj2rZKIgupy8LAac9NX5zxv+WvuZeAcOGInVYiryuS5WMY8flpweajfJ4uoRI6N5MvGFK09EgBZZSqGktJyVeLHAUZEjvIKduGRtim3wrpqTFNtmAkl3iXhOYkUhUlUWNTkuEH2vHMq3irpgFrL/7uXQcB/r18VIjXaxJDZlbY19bDrV1PdsGmTEhpFStN2izSEp+3gchs//8IqxpZgmXFNHPWNQdLVX9/pjansYd+eR6tT2yObYKaXlo8B3UZlvh2XeNynDIz9iNUzZeEzysdj9UJV+Gnm/aGd+oo6n+vVRKOe2Rmky5AnEwLQcSLy1IpRAZdUZlVMGxiIZuAnsRhmwZAGIhc7DE4ay+Gv8hroVhvRe78+pZ4Opv5HD7g9VN1x2MCANUrw0uAPmueq6EwDGtAFqCt1DnbMrvooXAHtPfsHvSjQesh/TVoIndeiD9j1I/rSP5OmV6PEQuorplWsBlsLRdGf3oisisyrupWCb9DXmveDIOgQqtD1lGddO7NkFsFLCiaXq94+EZxBu4ih/hqWcWFFoZ5pIpr4HcJU3Hm7qv+DWp2XLGDyj6zy7EC74tQwo1TE2MhQeYjb3jal3p6G0nqSXd91nlzJOjE7wBHsNe1XuhO1Ye6ET/jFSeo8BIyrugl4=
      on:
        tags: true
        condition: -z $SOURCEDEPLOY
