version: 1.0.{build}

clone_depth: 1

configuration:
    - Release

os: Visual Studio 2015
image: Visual Studio 2015

platform:
    - x86
    - x64

environment:
    TWINE_PASSWORD:
        secure: kTga6+rLL1fNpKqFNcX0QZNyqiYaHsEfSS4k6wvUoTE=
    matrix:
        - PYTHON: C:\Python35
          PYTHON_VERSION: 35
        - PYTHON: C:\Python36
          PYTHON_VERSION: 36
        - PYTHON: C:\Python37
          PYTHON_VERSION: 37

matrix:
    fast_finish: true

install:
    - IF DEFINED PYTHON (IF "%platform%" == "x64" SET PYTHON=%PYTHON%-x64)
    - IF DEFINED PYTHON SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
    - IF DEFINED PYTHON pip install pytest
                                    pytest-runner
                                    setuptools
                                    pybind11
                                    hypothesis
                                    twine
                                    wheel

before_build:
    - IF "%platform%" == "x64" set W64="-GVisual Studio 14 2015 Win64"
    - git fetch --tags

build_script:
    - ps: |
          mkdir build
          pushd build
    - cmake %APPVEYOR_BUILD_FOLDER%
            %W64%
            -DCMAKE_CXX_FLAGS=/D_CRT_SECURE_NO_WARNINGS
    - cmake --build .
            --config %configuration%
    - ps: |
          popd
          pushd python
          python setup.py bdist_wheel
          popd

test_script:
    - ps: pushd build
    - ctest --build-config %configuration% --output-on-failure
    - ps: popd

before_deploy:
    - ps: pushd build/python

after_deploy:
    - ps: popd

deploy_script:
    - ps: |
          Write-Host "TAG: $env:APPVEYOR_REPO_TAG"
          If ($env:APPVEYOR_REPO_TAG -eq "false") { return }

          Write-Host "Uploading wheels to pypi"
          Invoke-Expression "twine upload -u statoil-travis --skip-existing dist/*"
          If ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }
